services:
  postgres:
    image: postgres:15-alpine
    container_name: proctor_postgres
    environment:
      POSTGRES_DB: proctorstream
      POSTGRES_USER: proctor_user
      POSTGRES_PASSWORD: proctor_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: proctor_redis
    ports:
      - "6379:6379"

  minio:
    image: zenko/cloudserver:latest
    container_name: proctor_minio
    environment:
      ENDPOINT: minio
      S3BACKEND: file
      LOG_LEVEL: info
    ports:
      - "9000:8000"
    volumes:
      - minio_data:/usr/src/app/localData

volumes:
  postgres_data:
  minio_data: